name: notificarimud

services:
  postgresql:
    image: postgres:18
    container_name: notificari-mud-postgres
    restart: unless-stopped
    volumes:
      - notificari-mud-db:/var/lib/postgresql
    environment:
      - POSTGRES_USER=notificariMud
      - POSTGRES_DB=notificariMud
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 127.0.0.1:5442:5432

volumes:
  notificari-mud-db:
