# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NmZkNTJkMGQwMjM4NTRmYjg1ZDE3NTFmODdkNTlmZjRlN2FmODMxOTk3NTBmODc2YmFlZGI2NTA2NzhjYTU3YzhiOTc5NTc4ZTI1Zjc4YWU1N2IzYzE4ZDcwM2E5ZGU5OWVhMmQ3NmRlMTRhZTY4MWYxYThhMzZiZGY0YTdhNDk=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: notificariMud
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: notificariMud
    password:
